### ISSUE TITLE
Provide a way to control the preview image quality

### ISSUE THREAD

**Issue by rstepanenko** [adamchaboryk/gifa11y#8]
For initially paused gifs: it would be very helpful if I can increase the still image quality that is generated; I understand the implications for the page load, however, it is important in some cases to have a nice-looking and sharp still.

**Comment by adamchaboryk** [comment]
Hi @rstepanenko, thanks for your feedback. I think I achieved what you're suggesting. I created a new prop called `useDevicePixelRatio` which uses the [devicePixelRatio property](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio), as suggested by this MDN article: [Optimizing canvas - scaling for high resolution displays.](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas#scaling_for_high_resolution_displays)

Please give it a try, and let me know if there's any difference. Otherwise, please let me know if you have any other suggestions or would like to help improve with a PR.

Cheers

**Comment by rstepanenko** [comment]
OMG @adamchaboryk thank you so much, it looks beautiful now after this change! I would like to donate a bit towards the coffee fund for your project, can you please indicate how to do that?

Regards,
Roman.

**Comment by adamchaboryk** [comment]
Woot!! 🤠 Glad it works for you. Thank you for the feedback. I wouldn’t have looked into optimizing the `canvas` image if it weren’t for your comment. No coffee fund — treat yourself instead!

Cheers
